const api_url = {
    "generate_api": "https://app-quizexpert.local.ftech.ai/api/v1/generate",
    "feedback_api": "https://app-quizexpert.local.ftech.ai/api/v1/feedback",
    "fib_api": "https://app-quizexpert.local.ftech.ai/api/v1/generate_fib",
    "generate_from_book": "https://app-quizexpert.local.ftech.ai/api/v1/generate_from_book"
}

const maximumSize = 10 * 1024 * 1024

const timeout = 60000;

const generate_domain = {
    "none": {
        "name": "",
        "none": "",
    },
    "faq": {
        "name": "FAQs",
        "simple-question": "Đơn giản"
    },
    "english": {
        "name": "Tiếng Anh",
        "simple-question": "Đơn giản",
        "multiple-choices": "Trắc nghiệm",
        "fill-in-the-blank": "Điền vào chỗ trống"
    },
    "history": {
        "name": "Lịch sử",
        "simple-question": "Đơn giản",
        "multiple-choices": "Trắc nghiệm",
    },
    "history_textbook": {
        "name": "Lịch sử - SGK",
        "simple-question": "Đơn giản",
        "multiple-choices": "Trắc nghiệm",
    }
}

var history_content = null;
const history_path = "/questgen/data/history_textbook_highschool_vn_w_grades_data.json"

const example = {
    "faq_simple-question": ["Vụ trẻ em rơi vào cọc ống bê tông ở Đồng Tháp là một vụ tai nạn liên quan đến an toàn thi công công trình xây dựng diễn ra tại tỉnh Đồng Tháp vào ngày 31 tháng 12 năm 2022, khi một bé trai 10 tuổi có tên Thái Lý Hạo Nam rơi xuống miệng hố chứa cọc ống bê tông bên trong với đường kính 25 cm và được đóng sâu 35 m dưới lòng đất. Sau 3 ngày cứu hộ không thành, Thủ tướng Phạm Minh Chính đã gửi Công điện hỏa tốc yêu cầu chính quyền địa phương thực hiện cứu hộ. Vào ngày 4 tháng 1 năm 2023, chính quyền địa phương đã nhận định bé Thái Lý Hạo Nam 10 tuổi đã tử vong trong tình trạng đa chấn thương. Tuy nhiên, công tác giải cứu vẫn chưa được hoàn tất. Đến rạng sáng ngày 20 tháng 1, tức 29 Tết Nguyên Đán 2023, thi thế bé trai Hạo Nam đã được đưa lên khỏi mặt đất.",
        "Năm nay, phương án thi tốt nghiệp THPT được giữ ổn định như nhiều năm qua. Thí sinh THPT làm 4 bài thi, gồm 3 bài độc lập là Toán, Ngữ văn, Ngoại ngữ và một bài thi tổ hợp do thí sinh tự chọn. Nội dung thi nằm trong chương trình THPT, có sự tăng cường hợp lý một số nội dung liên quan đến vận dụng thực tiễn ở một số môn. Kỳ thi tốt nghiệp THPT 2023 sẽ được tổ chức trong 4 ngày 27, 28, 29 và 30/6/2023. Trong đó, vào ngày 27/6, thí sinh sẽ làm thủ tục dự thi. Hai ngày thi chính thức là 28 và 29/6. 30/6 là ngày thi dự phòng. Ngoài ra, theo dự thảo sửa đổi quy chế thi tốt nghiệp THPT công bố đầu tháng 1, Bộ GD&ĐT điều chỉnh một số vấn đề kỹ thuật để tăng cường kỷ cương thi cử. Theo đó, thí sinh không được mang thiết bị ghi âm, ghi hình vào phòng thi, chỉ được mang bút viết, bút chì, compa, tẩy, thước kẻ, máy tính bỏ túi không có chức năng soạn thảo văn bản và Atlat Địa lý Việt Nam (khi thi môn Địa lý).",
        "Tối 29/10/2022, thảm kịch giẫm đạp kinh hoàng đã xảy ra tại quận Itaewon, Seoul, Hàn Quốc khi hàng chục nghìn người đổ về đây tham dự lễ hội Halloween và chen lấn, xô đẩy nhau trong một con hẻm dốc, hẹp. Vụ việc trở thành thảm kịch giẫm đạp chết chóc nhất lịch sử Hàn Quốc với 158 người thiệt mạng, trong đó có 26 người nước ngoài. Trước đó, tối 1/10/2022, một vụ giẫm đạp và xô xát đã xảy ra tại sân vận động Kanjuruhan ở Malang Indonesia khiến hơn 130 người đã thiệt mạng và hàng trăm người bị thương, biến đây trở thành thảm kịch tồi tệ nhất lịch sử bóng đá. Hai thảm kịch giẫm đạp xảy ra chỉ trong vòng một tháng với mức độ nghiêm trọng chưa từng có đã bộc lộ lỗ hổng của lực lượng chức năng hai nước trong kiểm soát đám đông và phản ứng với sự cố, đồng thời gióng lên hồi chuông cảnh báo về nguy cơ tiềm ẩn đối với an ninh, an toàn sự kiện hậu COVID-19.",
        "ChatGPT, viết tắt của Chat Generative Pre-training Transformer, là một chatbot do công ty OpenAI của Mỹ phát triển và ra mắt vào tháng 11 năm 2022. ChatGPT được xây dựng dựa trên GPT-3.5 - một dòng mô hình ngôn ngữ lớn của OpenAI đồng thời được tinh chỉnh bằng cả hai kỹ thuật học tăng cường lẫn học có giám sát. ChatGPT được ra mắt dưới dạng nguyên mẫu vào tháng 11 năm 2022 và nhanh chóng thu hút sự chú ý nhờ việc nó có thể hồi đáp chi tiết và trả lời lưu loát trên nhiều lĩnh vực kiến thức khác nhau. Độ chính xác không đồng đều về dữ kiện thực tế của nó được xác định là mặt hạn chế đáng kể. Sau khi phát hành ChatGPT, OpenAI được định giá 29 tỷ USD.",
        "COVID-19 (từ tiếng Anh: coronavirus disease 2019 nghĩa là bệnh virus corona 2019)[10] là một bệnh đường hô hấp cấp tính truyền nhiễm gây ra bởi chủng virus corona SARS-CoV-2 và các biến thể của nó. Đây là một loại virus được phát hiện điều tra ổ dịch bắt nguồn từ khu chợ lớn chuyên bán hải sản và động vật ở Vũ Hán, tỉnh Hồ Bắc, Trung Quốc. Virus gây viêm đường hô hấp cấp ở người và cho thấy có sự lây lan từ người sang người. Ngoài chủng virus corona mới phát hiện này, đã có 6 chủng virus corona khác được biết tới ngày nay có khả năng lây nhiễm ở người sang người. Bệnh được phát hiện lần đầu tiên trong đại dịch COVID-19 năm 2019–2020.[11] Phương thức lây truyền chủ yếu của nó hiện nay là lây truyền từ người sang người, thường được truyền thông qua các giọt dịch hô hấp mà con người hắt hơi, ho hoặc thở ra.[11] Một người nhiễm bệnh có thể xuất hiện các triệu chứng sau thời gian ủ bệnh kéo dài từ 2 đến 14 ngày, trung bình là 5 ngày, trong thời gian đó nó vẫn có thể truyền nhiễm. Cần thận trọng để giúp hạn chế lây truyền bệnh, bao gồm vệ sinh cá nhân tốt và rửa tay thường xuyên."],
    "english_simple-question": ["San Francisco-based Logistos Advisors, Inc. is seeking an energetic person with strong public-speaking skills to serve as a temporary replacement for an employee who is away on leave. Logistics delivers training classes on Internet security to large financial institutions and retail businesses worldwide. The successful applicant will be responsible for assisting with training sessions throughout Latin America. Although the sessions are delivered in English. At least one year of experience as a corporate trainer in any field is highly desirable. The work assignment is for 6 months, the first two weeks to be spent at the Logistics headquarters for initial training. Interested candidates should submit a cover letter and résumé to hr@logistosadvisors.com by March 1.",
        "Renewable energy captured from the wind, sun, Earth’s heat, tides, and from small dams is drawing record levels of investment as poor villagers and entire nations alike seek clean, abundant ways to fuel economic growth. Global investment in renewable energy set a new record of $30 billion in 2004, according to a new report from the Renewable Energy Policy Network for the 21st Century (REN21). Technologies such as wind, solar, biomass, geothermal, and small hydro now provide 160 gigawatts of electricity generating capacity – about four per cent of the world total – the report said. They are growing at rates of around 20-30 per cent per year, however, compared to two or three per cent for oil and gas.",
        "Ecotourism is an environmentally responsible form of travel to natural areas which aims to reduce the impact that tourism has on the natural environment, including the flora and fauna of the area. There are a number of guidelines provided for ecotourists when visiting fragile environments. Before taking a trip to any destination, it is recommended that eco-travellers educate themselves about the places they are visiting by reading guidebooks and travel articles. Tourists should also be aware of local history, culture and customs of the locals before arriving. One way to gain appreciation from local people and enrich the experience is to make the effort to learn enough of the language to be polite, for example: hello, please and thank you. When packing, it is not recommended for visitors to give sweets or cookies to local people in developing countries, instead give them clothes or pens. During the time staying at the place, it is important that ecotourists be aware of the local customs. Different cultural values including different concepts of time, personal space and communication are other things to keep in mind. For example, in America, using a firm handshake is considered appropriate to greet a stranger; however, in France it is common to kiss someone you greet on both cheeks. Ecotourists are highly recommended to use local transport, guides, hotels, restaurants or markets to benefit the local economy. They should also limit the waste discharged into the air or water by using bicycles instead of cars or motorbikes and not leaving litter or starting fires. When returning from the trip, visitors should support organizations or societies that follow eco-principles and share their experiences with others in order to increase awareness of environmental issues and the protection of precious species in the area",
        "British Somaliland became independent on 26 June 1960 as the State of Somaliland, and the Trust Territory of Somalia (the former Italian Somaliland) followed suit five days later. On 1 July 1960, the two territories united to form the Somali Republic, albeit within boundaries drawn up by Italy and Britain. A government was formed by Abdullahi Issa Mohamud and Muhammad Haji Ibrahim Egal other members of the trusteeship and protectorate governments, with Haji Bashir Ismail Yusuf as President of the Somali National Assembly, Aden Abdullah Osman Daar as the President of the Somali Republic and Abdirashid Ali Shermarke as Prime Minister (later to become President from 1967 to 1969). On 20 July 1961 and through a popular referendum, the people of Somalia ratified a new constitution, which was first drafted in 1960. In 1967, Muhammad Haji Ibrahim Egal became Prime Minister, a position to which he was appointed by Shermarke. Egal would later become the President of the autonomous Somaliland region in northwestern Somalia.",
        "Henna is an important part of Somali culture. It is worn by Somali women on their hands, arms, feet and neck during weddings, Eid, Ramadan, and other festive occasions. Somali henna designs are similar to those in the Arabian peninsula, often featuring flower motifs and triangular shapes. The palm is also frequently decorated with a dot of henna and the fingertips are dipped in the dye. Henna parties are usually held before the wedding takes place. Somali women have likewise traditionally applied kohl to their eyes. Usage of the eye cosmetic in the Horn region is believed to date to the ancient Land of Punt."],
    "english_multiple-choices": ["San Francisco-based Logistos Advisors, Inc. is seeking an energetic person with strong public-speaking skills to serve as a temporary replacement for an employee who is away on leave. Logistics delivers training classes on Internet security to large financial institutions and retail businesses worldwide. The successful applicant will be responsible for assisting with training sessions throughout Latin America. Although the sessions are delivered in English. At least one year of experience as a corporate trainer in any field is highly desirable. The work assignment is for 6 months, the first two weeks to be spent at the Logistics headquarters for initial training. Interested candidates should submit a cover letter and résumé to hr@logistosadvisors.com by March 1.",
        "Renewable energy captured from the wind, sun, Earth’s heat, tides, and from small dams is drawing record levels of investment as poor villagers and entire nations alike seek clean, abundant ways to fuel economic growth. Global investment in renewable energy set a new record of $30 billion in 2004, according to a new report from the Renewable Energy Policy Network for the 21st Century (REN21). Technologies such as wind, solar, biomass, geothermal, and small hydro now provide 160 gigawatts of electricity generating capacity – about four per cent of the world total – the report said. They are growing at rates of around 20-30 per cent per year, however, compared to two or three per cent for oil and gas.",
        "Ecotourism is an environmentally responsible form of travel to natural areas which aims to reduce the impact that tourism has on the natural environment, including the flora and fauna of the area. There are a number of guidelines provided for ecotourists when visiting fragile environments. Before taking a trip to any destination, it is recommended that eco-travellers educate themselves about the places they are visiting by reading guidebooks and travel articles. Tourists should also be aware of local history, culture and customs of the locals before arriving. One way to gain appreciation from local people and enrich the experience is to make the effort to learn enough of the language to be polite, for example: hello, please and thank you. When packing, it is not recommended for visitors to give sweets or cookies to local people in developing countries, instead give them clothes or pens. During the time staying at the place, it is important that ecotourists be aware of the local customs. Different cultural values including different concepts of time, personal space and communication are other things to keep in mind. For example, in America, using a firm handshake is considered appropriate to greet a stranger; however, in France it is common to kiss someone you greet on both cheeks. Ecotourists are highly recommended to use local transport, guides, hotels, restaurants or markets to benefit the local economy. They should also limit the waste discharged into the air or water by using bicycles instead of cars or motorbikes and not leaving litter or starting fires. When returning from the trip, visitors should support organizations or societies that follow eco-principles and share their experiences with others in order to increase awareness of environmental issues and the protection of precious species in the area",
        "British Somaliland became independent on 26 June 1960 as the State of Somaliland, and the Trust Territory of Somalia (the former Italian Somaliland) followed suit five days later. On 1 July 1960, the two territories united to form the Somali Republic, albeit within boundaries drawn up by Italy and Britain. A government was formed by Abdullahi Issa Mohamud and Muhammad Haji Ibrahim Egal other members of the trusteeship and protectorate governments, with Haji Bashir Ismail Yusuf as President of the Somali National Assembly, Aden Abdullah Osman Daar as the President of the Somali Republic and Abdirashid Ali Shermarke as Prime Minister (later to become President from 1967 to 1969). On 20 July 1961 and through a popular referendum, the people of Somalia ratified a new constitution, which was first drafted in 1960. In 1967, Muhammad Haji Ibrahim Egal became Prime Minister, a position to which he was appointed by Shermarke. Egal would later become the President of the autonomous Somaliland region in northwestern Somalia.",
        "Henna is an important part of Somali culture. It is worn by Somali women on their hands, arms, feet and neck during weddings, Eid, Ramadan, and other festive occasions. Somali henna designs are similar to those in the Arabian peninsula, often featuring flower motifs and triangular shapes. The palm is also frequently decorated with a dot of henna and the fingertips are dipped in the dye. Henna parties are usually held before the wedding takes place. Somali women have likewise traditionally applied kohl to their eyes. Usage of the eye cosmetic in the Horn region is believed to date to the ancient Land of Punt."],
    "history_simple-question": ["Gia Long (1802–1820) đóng đô ở Huế, ông cho xây dựng kinh đô Huế tương tự như Tử Cấm Thành ở Bắc Kinh (Trung Quốc). Gia Long và con trai Minh Mạng (cai trị 1820–1841) đã cố gắng xây dựng Việt Nam theo khái niệm và phương pháp hành chính của Trung Quốc thời nhà Thanh. Từ thập niên 1830, giới trí thức Việt Nam (đại diện tiêu biểu là Nguyễn Trường Tộ) đã nhận thấy sự tụt hậu và trì trệ của đất nước, họ đề nghị triều đình nên học hỏi phương Tây để phát triển công nghiệp – thương mại, nhưng các quan lại này chỉ là thiểu số. Đáp lại, vua Minh Mạng và những người kế tục Thiệu Trị (1841–1847) và Tự Đức (1847–1883) chọn chính sách đã lỗi thời là coi trọng phát triển nông nghiệp (dĩ nông vi bản), tiếp tục cấm buôn bán với nước ngoài. Ngoài ra, các vua Minh Mạng, Thiệu Trị và Tự Đức ngăn cấm truyền bá Công giáo mà họ coi là \"tả đạo\". Tiếp nối các thừa sai Dòng Tên dưới quy chế bảo trợ Bồ Đào Nha là các thừa sai Pháp và Tây Ban Nha đến truyền giáo từ nửa sau thế kỉ 17. Một số giáo sĩ Pháp nổi bật cũng hỗ trợ nhân lực và vật lực cho nhà Nguyễn trong cuộc chiến với nhà Tây Sơn dẫn đến chiến thắng của vua Gia Long.",
        "Sau Cách mạng Tân Hợi lật đổ triều đại Thanh, Trung Quốc rơi vào tình trạng cát cứ địa phương và hỗn chiến quân phiệt. Năm 1913, nhằm đổi lấy viện trợ và thừa nhận của Nga cho Chính phủ Bắc Dương, Viên Thế Khải ký kết \"Hiệp ước Trung-Nga-Mông\". Từ đó, thế lực người Nga xâm nhập Ngoại Mông Cổ. Cùng năm, Chính phủ Bắc Dương nhằm giải quyết vấn đề quốc khố trống rỗng nên đã vay từ tổ chức ngân hàng của năm quốc gia Anh, Pháp, Đức, Nga, Nhật tổng cộng 25 triệu bảng, đồng thời đồng ý lấy thuế muối, thuế hải quan để thế chấp, giao công việc quản lý muối cho người ngoài quản lý, bị nhìn nhận là làm mất chủ quyền, quốc gia chịu nhục. ",
        "Bắt nguồn từ thời kỳ Nam – Bắc triều, năm 1527, sau khi giành ngôi từ nhà Hậu Lê, Mạc Đăng Dung đã lập nên nhà Mạc. Nhà Hậu Lê (sử gọi là nhà Lê trung hưng) được tái lập vài năm sau đó với sự giúp đỡ của Nguyễn Kim, một tướng cũ và giành được sự kiểm soát khu vực từ Thanh Hóa vào Bình Định. Sau khi Nguyễn Kim chết, người con rể là Trịnh Kiểm đã giành quyền bính, 60 năm kế tiếp, Trịnh Kiểm và các con cháu của ông đã giành được chiến thắng trước nhà Mạc vào năm 1592 và mở đầu cho thời kỳ đặc biệt trong lịch sử phong kiến Việt Nam, thời kỳ vua Lê chúa Trịnh",
        "Ðến cuối thế kỷ VII, quân Java của Indonesia từ Biển Ðông lại tràn vào đánh phá Ea ryu (Phú Yên) và Kauthara- Ea a Trang (Khánh Hòa), một phần lớn dân chúng Chiêm Thành đã chạy lên cao nguyên M'Đrak tị nạn mang theo những văn hóa tập tục mẫu hệ, kiến trúc, trồng trọt và ngôn ngữ Chiêm Thành giai đoạn sơ khai có yếu tố Ấn Độ hóa hơn mà tạo thành các nhóm Rhangdé. Người Rang Đê được cho là tổ tiên của người Eđê và Jarai,đã được ghi chép khá nhiều trong các bia ký Champa. Vào năm 1283, quân Mông Cổ tràn xuống xâm lăng Champa. Trước đoàn quân hùng mạnh của Mông Cổ, vua Champa quyết định rút quân lên vùng Tây nguyên để ẩn náu. Theo ông Marco Polo, một nhà du hành Âu Châu, vua Champa chịu bỏ trống toàn bộ lãnh thổ đồng bằng cho quân Mông Cổ chiếm đóng. Trong suốt hai năm chờ đợi không giao chiến, vì thiếu lương thực, quân Mông Cổ tự rút lui ra khỏi Champa. Năm 1266, hoàng tử ChayNuk, con Jaya Paramesvaravarman II, lên kế vị, hiệu Indravarman V. Indravarman V tiếp tục giao hảo tốt với Đại Việt. Năm 1278, Indravarman V sai hai sứ giả (Bồ Tinh và Bồ Đột) sang Đại Việt xin bảo hộ và thành lập một liên minh chống lại quân Mông Cổ. Hay tin này, năm 1281, vua Nguyên (Hốt Tất Liệt) cử hữu thống chế Toa Đô (Sogatu) và tả thống chế Lưu Thâm cùng tham chính A Lý và Ô Mã Nhi mang 10 vạn thủy binh từ Quảng Châu sang Chiêm Thành buộc Indravarman V phải đích thân về Trung Quốc triều cống. Không chống nổi quân Mông Cổ, Indravarman V chịu đặt Chiêm Thành dưới sự bảo hộ của nhà Nguyên (Trung Quốc) năm 1282. Toa Đô được nhà Nguyên phong làm thống đốc toàn quyền cai trị xứ Chiêm Thành, tiểu vương Champa nào chịu theo quân Nguyên đều được phong làm phó vương.",
        "Đầu năm 1905, phong trào đấu tranh chống đế quốc, chống phong kiến của nhân dân Trung Quốc đã lan rộng khắp các tỉnh. Hoa kiều ở nước ngoài cũng nhiệt liệt hưởng ứng phong trào. Trước tình hình đó, Tôn Trung Sơn từ châu Âu về Nhật Bản, hội bàn với những người đứng đầu các tổ chức cách mạng trong nước để thống nhất lực lượng thành một chính đảng. Tháng 8 - 1905, Trung Quốc Đồng minh hội - chính đảng của giai cấp tư sản Trung Quốc ra đời. Tham gia tổ chức này có trí thức tư sản, tiểu tư sản, địa chủ, thân sĩ bất bình với nhà Thanh, cùng một số ít đại biểu công nông. Cương lĩnh chính trị của Đồng minh hội, dựa trên học thuyết Tam dân của Tôn Trung Sơn, nêu rõ: \"Dân tộc độc lập, dân quyền tự do, dân sinh hạnh phúc\". Mục tiêu của Hội là đánh đổ Mãn Thanh, khôi phục Trung Hoa, thành lập Dân quốc, thực hiện quyền bình đẳng về ruộng đất cho dân cày."],
    "history_multiple-choices": ["Gia Long (1802–1820) đóng đô ở Huế, ông cho xây dựng kinh đô Huế tương tự như Tử Cấm Thành ở Bắc Kinh (Trung Quốc). Gia Long và con trai Minh Mạng (cai trị 1820–1841) đã cố gắng xây dựng Việt Nam theo khái niệm và phương pháp hành chính của Trung Quốc thời nhà Thanh. Từ thập niên 1830, giới trí thức Việt Nam (đại diện tiêu biểu là Nguyễn Trường Tộ) đã nhận thấy sự tụt hậu và trì trệ của đất nước, họ đề nghị triều đình nên học hỏi phương Tây để phát triển công nghiệp – thương mại, nhưng các quan lại này chỉ là thiểu số. Đáp lại, vua Minh Mạng và những người kế tục Thiệu Trị (1841–1847) và Tự Đức (1847–1883) chọn chính sách đã lỗi thời là coi trọng phát triển nông nghiệp (dĩ nông vi bản), tiếp tục cấm buôn bán với nước ngoài. Ngoài ra, các vua Minh Mạng, Thiệu Trị và Tự Đức ngăn cấm truyền bá Công giáo mà họ coi là \"tả đạo\". Tiếp nối các thừa sai Dòng Tên dưới quy chế bảo trợ Bồ Đào Nha là các thừa sai Pháp và Tây Ban Nha đến truyền giáo từ nửa sau thế kỉ 17. Một số giáo sĩ Pháp nổi bật cũng hỗ trợ nhân lực và vật lực cho nhà Nguyễn trong cuộc chiến với nhà Tây Sơn dẫn đến chiến thắng của vua Gia Long.",
        "Sau Cách mạng Tân Hợi lật đổ triều đại Thanh, Trung Quốc rơi vào tình trạng cát cứ địa phương và hỗn chiến quân phiệt. Năm 1913, nhằm đổi lấy viện trợ và thừa nhận của Nga cho Chính phủ Bắc Dương, Viên Thế Khải ký kết \"Hiệp ước Trung-Nga-Mông\". Từ đó, thế lực người Nga xâm nhập Ngoại Mông Cổ. Cùng năm, Chính phủ Bắc Dương nhằm giải quyết vấn đề quốc khố trống rỗng nên đã vay từ tổ chức ngân hàng của năm quốc gia Anh, Pháp, Đức, Nga, Nhật tổng cộng 25 triệu bảng, đồng thời đồng ý lấy thuế muối, thuế hải quan để thế chấp, giao công việc quản lý muối cho người ngoài quản lý, bị nhìn nhận là làm mất chủ quyền, quốc gia chịu nhục. ",
        "Bắt nguồn từ thời kỳ Nam – Bắc triều, năm 1527, sau khi giành ngôi từ nhà Hậu Lê, Mạc Đăng Dung đã lập nên nhà Mạc. Nhà Hậu Lê (sử gọi là nhà Lê trung hưng) được tái lập vài năm sau đó với sự giúp đỡ của Nguyễn Kim, một tướng cũ và giành được sự kiểm soát khu vực từ Thanh Hóa vào Bình Định. Sau khi Nguyễn Kim chết, người con rể là Trịnh Kiểm đã giành quyền bính, 60 năm kế tiếp, Trịnh Kiểm và các con cháu của ông đã giành được chiến thắng trước nhà Mạc vào năm 1592 và mở đầu cho thời kỳ đặc biệt trong lịch sử phong kiến Việt Nam, thời kỳ vua Lê chúa Trịnh",
        "Ðến cuối thế kỷ VII, quân Java của Indonesia từ Biển Ðông lại tràn vào đánh phá Ea ryu (Phú Yên) và Kauthara- Ea a Trang (Khánh Hòa), một phần lớn dân chúng Chiêm Thành đã chạy lên cao nguyên M'Đrak tị nạn mang theo những văn hóa tập tục mẫu hệ, kiến trúc, trồng trọt và ngôn ngữ Chiêm Thành giai đoạn sơ khai có yếu tố Ấn Độ hóa hơn mà tạo thành các nhóm Rhangdé. Người Rang Đê được cho là tổ tiên của người Eđê và Jarai,đã được ghi chép khá nhiều trong các bia ký Champa. Vào năm 1283, quân Mông Cổ tràn xuống xâm lăng Champa. Trước đoàn quân hùng mạnh của Mông Cổ, vua Champa quyết định rút quân lên vùng Tây nguyên để ẩn náu. Theo ông Marco Polo, một nhà du hành Âu Châu, vua Champa chịu bỏ trống toàn bộ lãnh thổ đồng bằng cho quân Mông Cổ chiếm đóng. Trong suốt hai năm chờ đợi không giao chiến, vì thiếu lương thực, quân Mông Cổ tự rút lui ra khỏi Champa. Năm 1266, hoàng tử ChayNuk, con Jaya Paramesvaravarman II, lên kế vị, hiệu Indravarman V. Indravarman V tiếp tục giao hảo tốt với Đại Việt. Năm 1278, Indravarman V sai hai sứ giả (Bồ Tinh và Bồ Đột) sang Đại Việt xin bảo hộ và thành lập một liên minh chống lại quân Mông Cổ. Hay tin này, năm 1281, vua Nguyên (Hốt Tất Liệt) cử hữu thống chế Toa Đô (Sogatu) và tả thống chế Lưu Thâm cùng tham chính A Lý và Ô Mã Nhi mang 10 vạn thủy binh từ Quảng Châu sang Chiêm Thành buộc Indravarman V phải đích thân về Trung Quốc triều cống. Không chống nổi quân Mông Cổ, Indravarman V chịu đặt Chiêm Thành dưới sự bảo hộ của nhà Nguyên (Trung Quốc) năm 1282. Toa Đô được nhà Nguyên phong làm thống đốc toàn quyền cai trị xứ Chiêm Thành, tiểu vương Champa nào chịu theo quân Nguyên đều được phong làm phó vương.",
        "Đầu năm 1905, phong trào đấu tranh chống đế quốc, chống phong kiến của nhân dân Trung Quốc đã lan rộng khắp các tỉnh. Hoa kiều ở nước ngoài cũng nhiệt liệt hưởng ứng phong trào. Trước tình hình đó, Tôn Trung Sơn từ châu Âu về Nhật Bản, hội bàn với những người đứng đầu các tổ chức cách mạng trong nước để thống nhất lực lượng thành một chính đảng. Tháng 8 - 1905, Trung Quốc Đồng minh hội - chính đảng của giai cấp tư sản Trung Quốc ra đời. Tham gia tổ chức này có trí thức tư sản, tiểu tư sản, địa chủ, thân sĩ bất bình với nhà Thanh, cùng một số ít đại biểu công nông. Cương lĩnh chính trị của Đồng minh hội, dựa trên học thuyết Tam dân của Tôn Trung Sơn, nêu rõ: \"Dân tộc độc lập, dân quyền tự do, dân sinh hạnh phúc\". Mục tiêu của Hội là đánh đổ Mãn Thanh, khôi phục Trung Hoa, thành lập Dân quốc, thực hiện quyền bình đẳng về ruộng đất cho dân cày."]
}

function init_domain() {
    let domain = document.querySelector("#domain");
    domain.innerHTML = "";
    for (let [key, value] of Object.entries(generate_domain)) {
        var option = document.createElement("option");
        option.value = key;
        option.text = value["name"];
        domain.add(option);
    }
}

function parse_history_content() {

}

async function read_history_content() {
    await axios.get(history_path)
        .then(function (response) {
            history_content = response.data;
        }).catch(function (error) {
            console.log(error)
        })

}

read_history_content();
init_domain();